default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  username: admin
  password: password
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: sample

#production:
#  <<: *default
#  database: <%= ENV['DB_DATABASE'] %>
#  adapter: mysql2
#  encoding: utf8mb4
#  charset: utf8mb4
#  collation: utf8mb4_general_ci
#  host: <%= ENV['DB_HOST'] %>
#  username: <%= ENV['DB_USERNAME'] %>
#  password: <%= ENV['DB_PASSWORD'] %>